# Generated by Django 3.1.13 on 2021-08-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivefolder',
            name='is_super',
            field=models.BooleanField(default=False),
        ),
    ]
