# Generated by Django 3.1.13 on 2021-08-19 18:14

from django.db import migrations, models
import storage.models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_drivefolder_is_super'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivefolder',
            name='file',
            field=models.FileField(max_length=255, null=True, upload_to=storage.models.upload_file),
        ),
        migrations.AddField(
            model_name='drivefolder',
            name='is_folder',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='drivefolder',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='DriveFile',
        ),
    ]
